### ISSUE TITLE
Feature - Consider adding in/out column so one can see when an associated sign in record has been signed out

### ISSUE THREAD

**Issue by awallwork** [dylancbaker/SAR-Sign-In-Assist#2]
![UIScreen](https://user-images.githubusercontent.com/2356/122798832-e3377080-d275-11eb-8d31-bdceb5075152.jpg)

On activity maybe a column showing IN / Out - the colour coding currently indicates this function it but may not be as intuitive for some folks.

**Comment by dylancbaker** [comment]
<img width="623" alt="InOut" src="https://user-images.githubusercontent.com/77604534/122837449-f4e63b80-d2a8-11eb-9e6a-92ccb09f5bd2.png">
How about this? it will use less space than a full column
